version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres-db
    depends_on:
      - redis
      - db

  redis:
    image: "redis:alpine"
    restart: always

  db:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres-db
    ports:
      - "5432:5432"
